### ISSUE TITLE
how to install in an ember-cli app

### ISSUE THREAD

**Issue by shopapps** [aupac/ember-aupac-cascading-select#1]
Hi,

I am wanting to use this in an ember-cli app, however, the npm install method didn't install it enough to allow me to use it in my App? errored saying addon couldnt be found or similar.  so I tried copying the addon folder to the route of my app, then the file in  the components folder into the /app/components folder and the file in templates/components across as well.

this stopped any reference errors to not being able to find the addon...

it's not mentioned, but i assume you have to create the models in question and then link them with belongsTo and hasMany ?

in my controller i put:

items:[{
 label: 'Request Type',
 modelClass: 'request-type',
optionsValuePath: 'content.id',
optionsLabelPath: 'content.name'
},
{
 label: 'Sub Request Type',
 modelClass: 'request-sub-type',
optionsValuePath: 'content.id',
optionsLabelPath: 'content.name'
}]

then in the template i have:
{{aupac-cascading-select items=items selection=requestSubType store=controller.store}}

now i see a new error:

Error: `modelClass` is not only supported at the top level item not index 1

any help you can offer on how to get this working in an Ember-Cli App is appreciated..

thanks.

Paul.

**Comment by jackmatt2** [comment]
@shopapps, this should be working as a ember-cli addon already.  I will look into it for you.

**Comment by shopapps** [comment]
thanks.  It might be worth noting I am using ember-cli version 1.13.5 so i dont know if that has anything to do with it :-)

**Comment by jackmatt2** [comment]
@shopapps Thanks for raising this issue.  I have done a complete refactor of the code to make it compatible with 1.13.x version of ember. I have changed the API to reflect the ember 2.0 way of doing components (data down / actions up).  I have also removed all bootstrap coupling to make it available to a wider audience.  I have also converted it into a block form component so that people can customize the look and feel as they wish.

I can't publish to NPM until Monday as I don't have the password with me.  Until then you should be able to get it working as follows.

I guess you can be the guinea pig on this one: 

Can you delete anything related to ember-aupac-cascading-select from you codebase (anything you copy  pasted etc).

Inside package.json add the following entry to dev-dependencies.
"ember-aupac-cascading-select" : "1.1.0"

Download a zip version of the ember-aupac-cascading-select repo and unzip to /yourapp/node_modules/ember-cli-cascading-select

Change your component to use block form like this and feel free to customize as you wish:

``` javascript
{{#aupac-cascading-select items=items store=store action=(action (mut requestSubType)) as |control|}}
  <div>
      <label>{{control.label}}</label>
      {{view "select"
      content=control.content
      selection=control.selection
      optionValuePath=control.optionValuePath
      optionLabelPath=control.optionLabelPath
      prompt=control.prompt
      disabled=control.disabled
  </div>
  }}
{{/aupac-cascading-select}}
```

Let me know how you go.

**Comment by jackmatt2** [comment]
@shopapps can you hold off on the above.  I am actually going to decouple the control from ember-data also and the api will change a little. 

Cheers.

**Comment by jackmatt2** [comment]
@shopapps I have updated it on npm now to v1.1.0.  The API has changed a lot.  I have updated the docs and would suggest you look over them again.

**Comment by shopapps** [comment]
Yey, is working great now!  and the documentation makes so that even a beginner like me can understand it - great Job!

One quick question.  is there a way of hiding the form-group -> child select item if no store items are returned?

**Comment by shopapps** [comment]
oh!  and also i have a re-usable form, used for both new and edit routes.  is there a way of defaulting the selects so when editing all the correct values are already picked?

**Comment by jackmatt2** [comment]
@shopapps For the first question.  Yes, you can do this is the template.

install [ember-truth-helpers](https://github.com/jmurphyau/ember-truth-helpers), then you can do:

``` html
{{#if (eq content.length 0)}}
   //no content
{{else}}
   //has content
{{/if}}
```

For you second question; the use case seems valid but I will need to think how to implement this because that relies on each select knowing what options it should have in it when the page loads.

**Comment by shopapps** [comment]
Ok, cool I'll take a look at that.  In regards to filling in the current select values, for me they could be passed from the model as model.requesttype_id  and model.subrequesttype_id  as variables somewhere in the items array

**Comment by shopapps** [comment]
worth pointing out you need something like:  https://github.com/jmurphyau/ember-truth-helpers to get {{#if(eq a b)}}  to work :)
currently is still showing the select box for me even when empty, am just debugging now, in case I typo'd..

**Comment by shopapps** [comment]
found it.. I had to use:  {{#if (eq control.content.length 0) }}  hiding of an empty  select box now works - yey..

**Comment by jackmatt2** [comment]
Oh yeah, sorry - forgot about the control prefix.

**Comment by jackmatt2** [comment]
@shopapps, the current version 1.2.0 allows you to pre-populate the selections on page load.  Note that the api has changed a little and the store is no longer injected into the component, instead, I suggest using a computed property for the items, please refer to the README.md.

**Comment by shopapps** [comment]
Sounds cool.  I'm just trying to implement now to test... excuse my ignorance but how do i install the 1.2.0 tag version?

at the moment if i try 

```
ember install ember-aupac-cascading-select
```

it only install 1.13.1 <- ignore this i think it is my ember version :)

i also tried:

```
ember install 'ember-aupac-cascading-select#1.2.0'
```

but that errors
- thanks.

**Comment by shopapps** [comment]
ok, so I think i got it installed using:
    npm install --save  https://github.com/aupac/ember-aupac-cascading-select.git#1.2.0

however the issue I currently have is regardless of what choice is made on the first select box, the second always stays the same :(

here's my code:
in the router.js for the pod ( i had to put it here, because i was getting lots of 'no model found' errors when trying to populate from the controller.

```
afterModel: function(model, transition) {
    this.itemsUpdate(model);
},
itemsUpdate:  function(model) {

  console.log('itemsUpdate');
  var _parent = this;
  var store = this.store;

  console.log('itemsUpdate', model, store);
 // console.log('model.requestType B4 = ', model.requestType.id);

  // if(!model.requestType)    model.requestType = 5;
  // if(!model.requestSubType) model.requestSubType = 5;

  //console.log('model.requestType = ', model.requestType.id);

  var rt = (model.requestType !== null) ? model.requestType : 5;
var rst = (model.requestSubType !== null) ? model.requestSubType : 5;
    console.log('itemsUpdate', model);
    console.log('this', this);

  Ember.RSVP.all([
    store.fetch('requestType', rt),
    store.fetch('requestSubType', rst)
  ]).then(function(results) {
    console.log('RESULTS 0: ', results[0].id);
    console.log('RESULTS 1: ', results[1].id);

    var tempItems = [{
      content : function(parent) {
        return store.findAll('requestType');
      },
      extras : {
        label : 'Request Type',
        width : 'col-xs-6'
      },
      selection : results[0],
      optionValuePath: 'content.id',
      optionLabelPath: 'content.name',
    },
      {
        content : function(parent) {
          return store.findAll('requestSubType');
        },
        extras : {
          label : 'Request Sub Type',
          width : 'col-xs-6'
        },
        selection : results[1],
        optionValuePath: 'content.id',
        optionLabelPath: 'content.name',
      }];
    _parent.controllerFor('requests.edit').set('items',tempItems); 

  });
},
```

and in my template.hbs

```
{{#aupac-cascading-select items=items action=(action (mut selectedItem)) as |control|}}
{{#if (not-eq control.content.length 0) }}
  <div class="form-group">
    <label class="control-label col-sm-3">{{control.extras.label}}</label>
    <div class="col-sm-9">
        {{view "select"
        content=control.content
        selection=control.selection
        optionValuePath=control.optionValuePath
        optionLabelPath=control.optionLabelPath
        class = "form-control"
        prompt=control.prompt
        disabled=control.disabled
      }}
      <p class="info">{{control.content.desc}}</p>
      <p class="error">{{control.extras.errorMessage}}</p>
    </div>
  </div>
{{/if}}
{{/aupac-cascading-select}}
```

Do I need to create the 'selectedItem' action or something to manually update the values of the second select based on the current selection of the first?

And one really rookie question, how do i associate the select box to the  correct model param?  i.e. so in my save action i can just do 

```
this.get('model').save();
```

or  do i have to go get each select value and manually assign it before the save?

thanks..

**Comment by shopapps** [comment]
ok, so i fixed the not changing on each select.  I had to change the second 'content' to as follows:

```
return parent.get('requestSubTypes');
```

rather than ( store.findAll('requestSubTypes'); )

So now I am trying to extract the current values to apply them to the model...  I have tried
  actions: {
    selectedItem: function(a,b) {
      console.log('selectedItem Action: ', a, b);
      //this.get('model').set('ordertype',value);
    },
}

but this never gets triggered..
and even

```
selectedRequestTypeChange: function(selection) {
   console.log('selectedRequestTypeChange method', selection);
 }.observes('selectedItem'),
```

but this just returns the controller

i hav ealso tried at the save action:

```
model.set('requestType', this.items[0].selection.id);
    model.set('requestSubType', this.items[1].selection.id);
    this.get('model').save().then(function(request) {
      _parent.transitionToRoute(modelRoute);
    });
```

but the this.items is just the original items variable sent..

sorry if this seems like a dumb question, i'll go do some more googling in the meantime..

**Comment by shopapps** [comment]
ok...  so i discovered an option called selectionBinding:

```
selectionBinding: 'content.selectedObject'
```

but this broke the select when i tried to use it.

so then I removed:

```
action=(action (mut selectedItem))
```

and replaced it with:

```
action=selectedItem
```

which if i change the first item it sends 'null' to my selectedItem method but if  i change a sub item it sends the  the sub item to the method - which is good.  Looking at the source it looks like if you change the first item you purposely send 'null' is it possible to get this changed?  or make it a config option to enable/disable this?

many thanks...  awesome addon btw.. :)

**Comment by jackmatt2** [comment]
@shopapps sorry about that, I tagged the release after updating npm, I think this is what cased the issue.  I have now fixed it - can you try installing via `ember install ember-aupac-cascading-select`.  The reason null is sent when you change an item other than the final selection is because the slelection is no longer valid for the parent selection.  If you can you give me a valid use case for your scenario I will make it opt-in.

**Comment by shopapps** [comment]
HI,

I fixed the null issue by changing (in your example):

```
content : function(parent) {
      return store.findAll('requestSubType');
    },
```

to...

```
content : function(parent) {
      return parent.get('requestSubType');
    },
```

The show stopper I have now, is how to either bind each select (all of them) to their own model param (ideally) or if not how to read values out of each select so i can then assign them to a model param.

Have you got any ideas on how to do this?

thanks..

**Comment by jackmatt2** [comment]
You could do it in the content call.

``` javascript
const store = this.get('store');
const model = this.get('model');

...

content : function(parent) {
      model.set('requestType', parent);
      return parent.get('requestSubType');
},
```

**Comment by shopapps** [comment]
Getting close.. :D 

I have a simple parent child setup

model.requestType and model.requestSubType

on the second item if i put:

```
 content : function(parent) {
            model.set('requestType', parent.id);
            return parent.get('requestSubTypes');
        },
```

then the requestTyoe is adjusted to match the first select box when it is changed - perfect!!!
however how can i track the content change of the second item?  do i have to spoof an empty third item or similar?

**Comment by jackmatt2** [comment]
You just need to use the `content` method for `requestType`. Since `requestSubType` is the final selection, you can use the usual `action` supplied on the component to update it.

**Comment by shopapps** [comment]
thanks,

I'll try that again, but i found that when i tried this before with the action  mut set

```
action=(action (mut selectedItem)) 
```

then nothing happend and if i set the action to

```
action=selectedItem
```

then a method on my controller called selectItem was fired, however it had no scope  (this = null) so i couldn't do anything with it,

would you expect the action to be fired on the controller or the route for this?

thanks so far for your great help..

**Comment by jackmatt2** [comment]
I would expect the action to be called on the controller, then the route.  Can you try action=(action 'selectedItem')

**Comment by jackmatt2** [comment]
oh, maybe you need `action=(action (mut model.requestSubType ))`

**Comment by shopapps** [comment]
RESULT!!!!  yes that was what i was missing..

Thanks so much for your help!  the first option worked for me..

model.requestSubType is a string  and when i tried your second suggestion it was echoing out as:

```
model.requestSubType: <service-tracker@model:request-sub-type::ember1055:7>
```

whereas with your firt option i can set:

actions: {
    selectedItem: function(item) {
      this.get('model').set('requestSubType',item.id);
      return false;
    }
}
and it all works!

**Comment by jackmatt2** [comment]
ah, good. I would imagine `action=(action (mut model.requestSubType.id ))` would also work.

**Comment by jackmatt2** [comment]
ah, good.

**Comment by shopapps** [comment]
Yep, it all works well now...  if you want I can tidy up my code and give it to you as an example for ember-cli users if that helps at all?

**Comment by jackmatt2** [comment]
OK, that would be good.
