### ISSUE TITLE
Using fields from a single object in the store

### ISSUE THREAD

**Issue by jdhines** [aupac/ember-aupac-cascading-select#5]
This probably isn't an "issue" per se, but I didn't see anything in the document for how to achieve this. 
Basically the problem is that, rather than having a model and an object for each select, I have only one source object that I need to make selects out of.

So my API data of suppliers, in tabular form, looks like this

```
|    Supplier Type    |    Supplier Sub-Type    |    Supplier Name    | 
|---------------------|-------------------------|---------------------|
|       ABC           |          DEF            |     Acme Inc        |
|       ABC           |          GHI            |    Billboards Plus  |
```

My template will have one select for each, and I need them to cascade.
Is there a way to use this plug-in for this case, essentially reusing the same data each time, just filtering based on what was selected before?

**Comment by jackmatt2** [comment]
Yes, I can't see a problem with this.  Give it a try and post an example of you code if you are having issues.

**Comment by jdhines** [comment]
I remembered I actually had another issue which was, since I'm still on 1.11, I don't have the ability to use the `mut` helper, and I'm not sure how to get around needing that.

**Comment by jackmatt2** [comment]
That is OK, the mut helper is just a shorcut for updating a field without having to actually write the action yourself.

So

``` javascript
action=(action (mut model.account))
```

is the same as

``` javascript
action='updateAccount'
```

``` javascript
//in your controller
actions : {
  updateAccount: function(account) {
    this.set('model.account', account);
  }
}
```

**Comment by jdhines** [comment]
If there are three selects though, what do you update in the action? `account` looks like one field. The front page says `selectedItem` is the value of the last selection made, but I don't want just the last one, I need the values for each select to set a property on the model.

**Comment by jackmatt2** [comment]
The `action` will only fire for the very final item in the cascading selection. The idea being that the cascading selection is a narrowing search until you find the actual item you want.  If you need to keep track of every item in the cascading select you can save the `parent` item to the appropriate model field in the `content` function before returning the new array of items for the sub-select.

**Comment by jdhines** [comment]
I ended up creating my own component in the meantime using pretty standard POJ, but thanks for your help and input. I'm sure I'll need to do this again on this project, so I'll give yours a shot then!
